//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSE.Timetable
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// DisciplineKind.
    /// </summary>
    // *** Start programmer edit section *** (DisciplineKind CustomAttributes)

    // *** End programmer edit section *** (DisciplineKind CustomAttributes)
    [PublishName("DisciplineKind")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Name"})]
    [View("DisciplineKindE", new string[] {
            "Name as \'Название\'"})]
    [View("DisciplineKindL", new string[] {
            "Name as \'Название\'"})]
    public class DisciplineKind : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (DisciplineKind CustomMembers)

        // *** End programmer edit section *** (DisciplineKind CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (DisciplineKind.Name CustomAttributes)

        // *** End programmer edit section *** (DisciplineKind.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (DisciplineKind.Name Get start)

                // *** End programmer edit section *** (DisciplineKind.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (DisciplineKind.Name Get end)

                // *** End programmer edit section *** (DisciplineKind.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DisciplineKind.Name Set start)

                // *** End programmer edit section *** (DisciplineKind.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (DisciplineKind.Name Set end)

                // *** End programmer edit section *** (DisciplineKind.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(HSE.Timetable.DisciplineKind));
                }
            }
            
            /// <summary>
            /// "DisciplineKindE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DisciplineKindE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DisciplineKindE", typeof(HSE.Timetable.DisciplineKind));
                }
            }
            
            /// <summary>
            /// "DisciplineKindL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DisciplineKindL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DisciplineKindL", typeof(HSE.Timetable.DisciplineKind));
                }
            }
        }
    }
}
