//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSE.Timetable
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Room.
    /// </summary>
    // *** Start programmer edit section *** (Room CustomAttributes)

    // *** End programmer edit section *** (Room CustomAttributes)
    [PublishName("Room")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Number as \'Number\'",
            "Building as \'Building\'"})]
    [View("RoomE", new string[] {
            "Number as \'Номер\'",
            "Building as \'Корпус\'"})]
    [View("RoomL", new string[] {
            "Number as \'Номер\'",
            "Building as \'Корпус\'"})]
    public class Room : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private int fNumber;
        
        private int fBuilding;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        // *** Start programmer edit section *** (Room CustomMembers)

        // *** End programmer edit section *** (Room CustomMembers)

        
        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (Room.Number CustomAttributes)

        // *** End programmer edit section *** (Room.Number CustomAttributes)
        public virtual int Number
        {
            get
            {
                // *** Start programmer edit section *** (Room.Number Get start)

                // *** End programmer edit section *** (Room.Number Get start)
                int result = this.fNumber;
                // *** Start programmer edit section *** (Room.Number Get end)

                // *** End programmer edit section *** (Room.Number Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Number Set start)

                // *** End programmer edit section *** (Room.Number Set start)
                this.fNumber = value;
                // *** Start programmer edit section *** (Room.Number Set end)

                // *** End programmer edit section *** (Room.Number Set end)
            }
        }
        
        /// <summary>
        /// Building.
        /// </summary>
        // *** Start programmer edit section *** (Room.Building CustomAttributes)

        // *** End programmer edit section *** (Room.Building CustomAttributes)
        public virtual int Building
        {
            get
            {
                // *** Start programmer edit section *** (Room.Building Get start)

                // *** End programmer edit section *** (Room.Building Get start)
                int result = this.fBuilding;
                // *** Start programmer edit section *** (Room.Building Get end)

                // *** End programmer edit section *** (Room.Building Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Building Set start)

                // *** End programmer edit section *** (Room.Building Set start)
                this.fBuilding = value;
                // *** Start programmer edit section *** (Room.Building Set end)

                // *** End programmer edit section *** (Room.Building Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Room.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Room.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Room.CreateTime Get start)

                // *** End programmer edit section *** (Room.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Room.CreateTime Get end)

                // *** End programmer edit section *** (Room.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.CreateTime Set start)

                // *** End programmer edit section *** (Room.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Room.CreateTime Set end)

                // *** End programmer edit section *** (Room.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Room.Creator CustomAttributes)

        // *** End programmer edit section *** (Room.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Room.Creator Get start)

                // *** End programmer edit section *** (Room.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Room.Creator Get end)

                // *** End programmer edit section *** (Room.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Creator Set start)

                // *** End programmer edit section *** (Room.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Room.Creator Set end)

                // *** End programmer edit section *** (Room.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Room.EditTime CustomAttributes)

        // *** End programmer edit section *** (Room.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Room.EditTime Get start)

                // *** End programmer edit section *** (Room.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Room.EditTime Get end)

                // *** End programmer edit section *** (Room.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.EditTime Set start)

                // *** End programmer edit section *** (Room.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Room.EditTime Set end)

                // *** End programmer edit section *** (Room.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Room.Editor CustomAttributes)

        // *** End programmer edit section *** (Room.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Room.Editor Get start)

                // *** End programmer edit section *** (Room.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Room.Editor Get end)

                // *** End programmer edit section *** (Room.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Editor Set start)

                // *** End programmer edit section *** (Room.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Room.Editor Set end)

                // *** End programmer edit section *** (Room.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(HSE.Timetable.Room));
                }
            }
            
            /// <summary>
            /// "RoomE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomE", typeof(HSE.Timetable.Room));
                }
            }
            
            /// <summary>
            /// "RoomL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomL", typeof(HSE.Timetable.Room));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
