//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSE.Timetable
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Teacher.
    /// </summary>
    // *** Start programmer edit section *** (Teacher CustomAttributes)

    // *** End programmer edit section *** (Teacher CustomAttributes)
    [PublishName("Teacher")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Surname as \'Surname\'",
            "Name as \'Name\'",
            "MiddleName as \'Middle name\'"})]
    [View("TeacherE", new string[] {
            "Surname as \'Фамилия\'",
            "Name as \'Имя\'",
            "MiddleName as \'Отчество\'"})]
    [AssociatedDetailViewAttribute("TeacherE", "Discipline", "DisciplineE", true, "", "Дисциплины", true, new string[] {
            ""})]
    [View("TeacherL", new string[] {
            "Surname as \'Фамилия\'",
            "Name as \'Имя\'",
            "MiddleName as \'Отчество\'"})]
    public class Teacher : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fSurname;
        
        private string fName;
        
        private string fMiddleName;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private HSE.Timetable.DetailArrayOfDiscipline fDiscipline;
        
        // *** Start programmer edit section *** (Teacher CustomMembers)

        // *** End programmer edit section *** (Teacher CustomMembers)

        
        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.Surname CustomAttributes)

        // *** End programmer edit section *** (Teacher.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.Surname Get start)

                // *** End programmer edit section *** (Teacher.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (Teacher.Surname Get end)

                // *** End programmer edit section *** (Teacher.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.Surname Set start)

                // *** End programmer edit section *** (Teacher.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (Teacher.Surname Set end)

                // *** End programmer edit section *** (Teacher.Surname Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.Name CustomAttributes)

        // *** End programmer edit section *** (Teacher.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.Name Get start)

                // *** End programmer edit section *** (Teacher.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Teacher.Name Get end)

                // *** End programmer edit section *** (Teacher.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.Name Set start)

                // *** End programmer edit section *** (Teacher.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Teacher.Name Set end)

                // *** End programmer edit section *** (Teacher.Name Set end)
            }
        }
        
        /// <summary>
        /// MiddleName.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.MiddleName CustomAttributes)

        // *** End programmer edit section *** (Teacher.MiddleName CustomAttributes)
        [StrLen(255)]
        public virtual string MiddleName
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.MiddleName Get start)

                // *** End programmer edit section *** (Teacher.MiddleName Get start)
                string result = this.fMiddleName;
                // *** Start programmer edit section *** (Teacher.MiddleName Get end)

                // *** End programmer edit section *** (Teacher.MiddleName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.MiddleName Set start)

                // *** End programmer edit section *** (Teacher.MiddleName Set start)
                this.fMiddleName = value;
                // *** Start programmer edit section *** (Teacher.MiddleName Set end)

                // *** End programmer edit section *** (Teacher.MiddleName Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Teacher.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.CreateTime Get start)

                // *** End programmer edit section *** (Teacher.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Teacher.CreateTime Get end)

                // *** End programmer edit section *** (Teacher.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.CreateTime Set start)

                // *** End programmer edit section *** (Teacher.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Teacher.CreateTime Set end)

                // *** End programmer edit section *** (Teacher.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.Creator CustomAttributes)

        // *** End programmer edit section *** (Teacher.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.Creator Get start)

                // *** End programmer edit section *** (Teacher.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Teacher.Creator Get end)

                // *** End programmer edit section *** (Teacher.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.Creator Set start)

                // *** End programmer edit section *** (Teacher.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Teacher.Creator Set end)

                // *** End programmer edit section *** (Teacher.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.EditTime CustomAttributes)

        // *** End programmer edit section *** (Teacher.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.EditTime Get start)

                // *** End programmer edit section *** (Teacher.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Teacher.EditTime Get end)

                // *** End programmer edit section *** (Teacher.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.EditTime Set start)

                // *** End programmer edit section *** (Teacher.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Teacher.EditTime Set end)

                // *** End programmer edit section *** (Teacher.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.Editor CustomAttributes)

        // *** End programmer edit section *** (Teacher.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.Editor Get start)

                // *** End programmer edit section *** (Teacher.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Teacher.Editor Get end)

                // *** End programmer edit section *** (Teacher.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.Editor Set start)

                // *** End programmer edit section *** (Teacher.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Teacher.Editor Set end)

                // *** End programmer edit section *** (Teacher.Editor Set end)
            }
        }
        
        /// <summary>
        /// Teacher.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.Discipline CustomAttributes)

        // *** End programmer edit section *** (Teacher.Discipline CustomAttributes)
        public virtual HSE.Timetable.DetailArrayOfDiscipline Discipline
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.Discipline Get start)

                // *** End programmer edit section *** (Teacher.Discipline Get start)
                if ((this.fDiscipline == null))
                {
                    this.fDiscipline = new HSE.Timetable.DetailArrayOfDiscipline(this);
                }
                HSE.Timetable.DetailArrayOfDiscipline result = this.fDiscipline;
                // *** Start programmer edit section *** (Teacher.Discipline Get end)

                // *** End programmer edit section *** (Teacher.Discipline Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.Discipline Set start)

                // *** End programmer edit section *** (Teacher.Discipline Set start)
                this.fDiscipline = value;
                // *** Start programmer edit section *** (Teacher.Discipline Set end)

                // *** End programmer edit section *** (Teacher.Discipline Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(HSE.Timetable.Teacher));
                }
            }
            
            /// <summary>
            /// "TeacherE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeacherE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeacherE", typeof(HSE.Timetable.Teacher));
                }
            }
            
            /// <summary>
            /// "TeacherL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeacherL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeacherL", typeof(HSE.Timetable.Teacher));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
